### ISSUE TITLE
Wireframe(landing page for employees)

### ISSUE THREAD

**Issue by ShaunVSIT** [personryan/ICT-2101-P4-1#12]
12/9/22: Start creating wireframe
16/9/22: Show client wireframe for feedback and improve wireframe.

**Comment by personryan** [comment]
19/9/22: Finished wireframe for employees (Deadline met)




![Image](https://user-images.githubusercontent.com/90229655/191943295-57a0b8e0-93db-4286-8439-d498127a6e38.png)
