### ISSUE TITLE
Individual Members Task Reflections for M1 Report

### ISSUE THREAD

**Issue by personryan** [personryan/ICT-2101-P4-1#13]

**Comment by ShaunVSIT** [comment]
Individual reflections have been added to M1 report on 24/09/22 (Deadline met)



![Image](https://user-images.githubusercontent.com/91268180/192187962-25ae40da-4aa4-499d-94dd-dc69f9b895c8.png)



![Image](https://user-images.githubusercontent.com/91268180/192187986-52abd1be-6901-480b-97a7-2b8e3ecf78b1.png)



![Image](https://user-images.githubusercontent.com/91268180/192188013-111a1828-a2c7-4421-80ef-3cae476411ed.png)



![Image](https://user-images.githubusercontent.com/91268180/192188028-755834f0-3066-477c-908e-87f186906f70.png)
