### ISSUE TITLE
Security requirements Planning

### ISSUE THREAD

**Issue by ShaunVSIT** [personryan/ICT-2101-P4-1#14]
16/9/22: Start of security requirements planning

**Comment by ShaunVSIT** [comment]
Completed on 19/09/22.  (Deadline met)

**Comment by personryan** [comment]
PFA for security planning done for the report


![Image](https://user-images.githubusercontent.com/90229655/191939941-42bb9c41-d52a-46b3-b655-0866e3f43237.png)
