### ISSUE TITLE
Clarify requirements with client

### ISSUE THREAD

**Issue by personryan** [personryan/ICT-2101-P4-1#2]
16/9/22: ask client questions and show wireframe.

**Comment by ShaunVSIT** [comment]
Closed 1st round on 16/09/22

**Comment by personryan** [comment]
16/9/22: client meeting done, questions have been answered. PFA for client meeting minutes.
https://docs.google.com/document/d/1LbCkXLTeMIrjHqPp5fF5YUZqXTcNNbMldBWyihpE6Yc/edit
