### ISSUE TITLE
4.2 Architectural Design

### ISSUE THREAD

**Issue by personryan** [personryan/ICT-2101-P4-1#22]
26/9/22: To start developing our architectural design

28/10/22: Final consult with profs to finalise architectural design
utilised:
-layered architecture
-MVC
-ECB
-client server

![Image](https://user-images.githubusercontent.com/90229655/198755537-26cd27bd-151e-43d5-90ef-eaf5fda6fe87.png)

**Comment by Uygnis** [comment]
It was definitely a journey creating this architectural design with everyone!
