### ISSUE TITLE
4.2.1 Component Diagram

### ISSUE THREAD

**Issue by personryan** [personryan/ICT-2101-P4-1#23]
3/10/22: To start development of component diagram

**Comment by DoubleBounce** [comment]
17/10/22: To review component diagram @personryan 

![Image](https://user-images.githubusercontent.com/79396686/196245508-447ef686-bd8f-4abe-b52f-b9423ceef4ee.png)

https://app.diagrams.net/#G1bKyCQb68E2muU7kgBcfzB6ZInRaPm5Na

**Comment by personryan** [comment]
18/10/22: The component looks okay, we can check with the profs if its okay 
21/10/22: After consultation, prof recommended to use MVC pattern for component diagram
23/10/22: Created component diagram using MVC pattern, to consult prof @DoubleBounce Please review it

![Image](https://user-images.githubusercontent.com/90229655/197377628-a1365239-5c2e-454c-85e4-414576424b59.png)

**Comment by personryan** [comment]
28/10/22:Redesigned component diagram with layered architecture, Model–View–Controller (MVC), client-server architecture and Entity Control Boundary (ECB) PFA for the updated diagram. Reviewed by @DoubleBounce 


![Image](https://user-images.githubusercontent.com/90229655/198755470-669f58b5-5009-4058-b1b5-1444d8645e53.png)

Encapsulated components:


![Image](https://user-images.githubusercontent.com/90229655/198755574-f0032743-72de-40ba-b94c-12fbe86a8b58.png)

**Comment by ShaunVSIT** [comment]
29/10: Quick update to component composition table:

![Image](https://user-images.githubusercontent.com/91268180/198839720-7899959b-d0ab-4c5f-9a38-b4d9994b8fd5.png)

**Comment by DoubleBounce** [comment]
Reviewed on 29 Oct 2022. 
Closing this issue now.
