### ISSUE TITLE
4.3.5 Sequence Diagrams

### ISSUE THREAD

**Issue by personryan** [personryan/ICT-2101-P4-1#25]
10/10/22: To start development of sequence diagram

**Comment by ShaunVSIT** [comment]
13/10/22:

Delegation of work:

UCD 1- 6: Jon
UCD 7-10: Ryan
UCD 11-14: Shaun

**Comment by Uygnis** [comment]
Hi all, UCD 1-6 done 
![UML Diagram-Sequence Diagrams drawio](https://user-images.githubusercontent.com/75312898/196025209-387d6178-ea14-4e5d-bb06-cd0bb0b5aaea.png)

Could either @personryan or @ShaunVSIT review it and see if there's anything I should change?

**Comment by ShaunVSIT** [comment]
Hi Jon, thanks for the effort, all looks good to me!

**Comment by personryan** [comment]
Hi all, 7-10 UCD sequence diagrams are done. Could either @Uygnis, @ShaunVSIT, @DoubleBounce review it for any changes to be made. 😄 


![Image](https://user-images.githubusercontent.com/90229655/196676468-dc2bb6c4-f5b8-4339-bd89-7a50abb1a73c.png)



![Image](https://user-images.githubusercontent.com/90229655/196676666-31d65531-0ef4-48e8-91d8-41a029092731.png)



![Image](https://user-images.githubusercontent.com/90229655/196676729-d452d39d-51f0-4ddf-bb67-4230797db741.png)



![Image](https://user-images.githubusercontent.com/90229655/196676792-3e974b92-e428-4fe2-a156-0e009df167ba.png)

**Comment by ShaunVSIT** [comment]
Hey @personryan, thanks for the effort, you'll need to update the return message arrows, they should be flat arrowheads instead

**Comment by ShaunVSIT** [comment]
UCD 11-14 sequence diagrams are done, do note **I've split UCD 14 into 14 and 15** for clearer sequences, will be updated in the report accordingly.

@Uygnis could you kindly review the diagrams and alert me of any errors, thank you!


![Image](https://user-images.githubusercontent.com/91268180/196718501-a8845198-41da-42ad-8f03-5acb95e4b870.png)

**Comment by Uygnis** [comment]
@ShaunVSIT looks great. Just a small change for uc11-14, do include the success scenarios within the alt fragments too

**Comment by ShaunVSIT** [comment]
Hi all, our sequence Diagrams were reviewed by the professors during our labtorial on 21/10 and these are the pending changes:

- Each diagram should complete the main flow (back to USER) before the alternate scenarios are shown 
- Database actor should return a result set for all queries 
- Changes to control classes have been made in the ECB and will need to be updated once finalized

Owners of each diagram please take note and make changes as necessary, cheers

**Comment by personryan** [comment]
29/10/22: Final updates of sequence diagrams, reviewed by @DoubleBounce 


![Image](https://user-images.githubusercontent.com/90229655/198818051-a44ceb02-a55c-46b9-997a-5a324c3beda6.png)



![Image](https://user-images.githubusercontent.com/90229655/198818389-b03a8aec-5ef7-4692-b4ba-1eed70b25162.png)



![Image](https://user-images.githubusercontent.com/90229655/198818448-d49c84f2-dc71-4ff8-a825-4bfd82bc51e0.png)

**Comment by ShaunVSIT** [comment]
29/10: Thanks for the effort everyone, updated diagrams have been added to the report and will be closing this issue.
