### ISSUE TITLE
5.1 Prototype

### ISSUE THREAD

**Issue by personryan** [personryan/ICT-2101-P4-1#26]
24/10/22: To start prototype development

**Comment by ShaunVSIT** [comment]
Prototype completed on 24/11, please refer to the other issues opened for specific pages

**Comment by DoubleBounce** [comment]
Prototypes can be viewed using these links:

Staff: 
https://www.figma.com/proto/4lI6XV0cZOifpHER3bquuG/WEEWOO?node-id=5%3A765&scaling=min-zoom&page-id=5%3A765&starting-point-node-id=238%3A3574

Manager:
https://www.figma.com/proto/4lI6XV0cZOifpHER3bquuG/WEEWOO?node-id=5%3A765&scaling=min-zoom&page-id=5%3A765&starting-point-node-id=238%3A3574

IT Admin:
https://www.figma.com/proto/4lI6XV0cZOifpHER3bquuG/WEEWOO?node-id=5%3A765&scaling=min-zoom&page-id=5%3A765&starting-point-node-id=238%3A3574
