### ISSUE TITLE
5.3 White Box Testing

### ISSUE THREAD

**Issue by personryan** [personryan/ICT-2101-P4-1#28]
27/10/22: To start white box testing

**Comment by ShaunVSIT** [comment]
Control flow graph:

![Image](https://user-images.githubusercontent.com/91268180/204075901-3ceb7f90-a27a-49cd-aa2a-1a0cefcadb9e.png)

Cyclomatic complexity:

![Image](https://user-images.githubusercontent.com/91268180/204075909-63df1c4d-d131-4350-9304-1d39facd801f.png)

Paths:

![Image](https://user-images.githubusercontent.com/91268180/204075915-a46ab8d4-7543-4bb2-b6e5-adb328f1df6f.png)

Tests:

![Image](https://user-images.githubusercontent.com/91268180/204075929-7d0d3dbd-6a41-47db-9700-a619fcb2d8ff.png)
