### ISSUE TITLE
Create questions for client meeting

### ISSUE THREAD

**Issue by ShaunVSIT** [personryan/ICT-2101-P4-1#3]
29/8/22: Formulate questions

**Comment by ShaunVSIT** [comment]
Initial questions created and discussed, to be refined before client meeting
Finished at 2/9/22 (Deadline met)

**Comment by personryan** [comment]
Questions Drafted:

![Image](https://user-images.githubusercontent.com/90229655/191940506-11084d7a-9908-4e47-8435-deef648ab9a1.png)


![Image](https://user-images.githubusercontent.com/90229655/191940658-c7c0d92b-50ab-4520-99c1-1618e1c00925.png)
