### ISSUE TITLE
4.3.1 Entity Classes

### ISSUE THREAD

**Issue by personryan** [personryan/ICT-2101-P4-1#34]
13/10/22: created entity classes with team members
13/10/22:  To be reviewed by Shaun by 14/10/22

**Comment by ShaunVSIT** [comment]
![Image](https://user-images.githubusercontent.com/90229655/196037001-5fac3499-c743-4b7f-984d-0d31514210ca.png)


![Image](https://user-images.githubusercontent.com/90229655/196037023-0ca10595-bac1-4b00-98e6-a9b2694980b1.png)



14/10/22: Entities look complete, lgtm!!

**Comment by personryan** [comment]
28/10/22: Finalised ECB diagram done. reviewed by @Uygnis 


![Image](https://user-images.githubusercontent.com/90229655/198755625-8f070ff3-206f-4332-ba85-58ad491c8378.png)
