### ISSUE TITLE
4.3.2 Control Classes

### ISSUE THREAD

**Issue by DoubleBounce** [personryan/ICT-2101-P4-1#35]
3/10/22: create control class

**Comment by DoubleBounce** [comment]
![Image](https://user-images.githubusercontent.com/79396686/196245239-b81101dc-5620-4b43-a919-b6297f3c499f.png)

https://app.diagrams.net/#G1bKyCQb68E2muU7kgBcfzB6ZInRaPm5Na

**Comment by personryan** [comment]
18/10/22: Review control classes

The control classes looks good 😄

**Comment by personryan** [comment]
28/10/22: Finalise ECB diagram with every member


![Image](https://user-images.githubusercontent.com/90229655/198755710-729920b7-86cf-49b6-98ac-ab8d58741e2b.png)

**Comment by DoubleBounce** [comment]
28/10/22: Touched up ECB diagram. This is the final one. Reviewed by Lim Ryan. Issue closed.

![Image](https://user-images.githubusercontent.com/79396686/198895625-486de90b-535f-4e1c-9ca6-718de269bd58.png)
