### ISSUE TITLE
4.3.3 Boundary Classes

### ISSUE THREAD

**Issue by Uygnis** [personryan/ICT-2101-P4-1#36]
identify boundary objects that will interact with actors

**Comment by Uygnis** [comment]
**Identified Boundaries:**
1. ITAdminPage: IT admin will interact with this page for account creation/deletion/editing
2. StaffProfilePage: Staff will interact with this page to view profile, create profile, and edit profile
3. JobAllocationPage: Managers will interact with this page to view staff utilization, accept and reject staff job rejection request, and allocate jobs
4. DashboardPage: Staff will interact with this page to add/delete/edit availability, reject/accept jobs

@DoubleBounce @ShaunVSIT @personryan, please review the above boundaries that are identified and see if there's anything I should include. Thanks!

**Comment by personryan** [comment]
28/10/22: Looks Good, from that we have created the finalised ECB diagram reviewed by @ShaunVSIT 


![Image](https://user-images.githubusercontent.com/90229655/198755690-7f5a3270-e931-4191-94ad-6adb5b744411.png)

**Comment by Uygnis** [comment]
@personryan @ShaunVSIT Great!
