### ISSUE TITLE
4.1.1 Update Use Case Diagram

### ISSUE THREAD

**Issue by ShaunVSIT** [personryan/ICT-2101-P4-1#37]
Use Case Diagram to be updated per M1 Review @Uygnis 

Deadline: 24/10

**Comment by Uygnis** [comment]
Updated Use Case Diagram as per the M1 Review


![Image](https://user-images.githubusercontent.com/75312898/197526057-f73b47f4-e4a6-47a1-9a69-ff82d3eb81b2.png)



Previously reviewed by @personryan
