### ISSUE TITLE
4.4 Project Planning

### ISSUE THREAD

**Issue by ShaunVSIT** [personryan/ICT-2101-P4-1#39]
23/10: To update existing project planning, leading up to M2 
Updated WBS

![Image](https://user-images.githubusercontent.com/90229655/198818927-ce907b7c-1022-454e-817e-cd0bd35b0acc.png)

**Comment by personryan** [comment]
29/10/22: Updated Gantt chart to match closed issues


![Image](https://user-images.githubusercontent.com/90229655/198818885-44e77c0c-1997-48e7-ac80-22eca7b711f0.png)

**Comment by personryan** [comment]
30/10/22: Officially closing the gantt chart as M2 has been completed


![Image](https://user-images.githubusercontent.com/90229655/198869681-2a5fdb21-37b1-49bf-91b8-cf75a673f70c.png)
