### ISSUE TITLE
4.4.1 Software Estimation

### ISSUE THREAD

**Issue by Uygnis** [personryan/ICT-2101-P4-1#42]
Software estimated updated 

![Image](https://user-images.githubusercontent.com/75312898/197400302-d04e79df-6307-40b4-967f-273cd8cfd85f.png)

Do help to review @DoubleBounce @ShaunVSIT @personryan

**Comment by personryan** [comment]
29/10/22: Looks good @Uygnis I see that it has been updated in the report as well, i think we are ready to closes the issue


![Image](https://user-images.githubusercontent.com/90229655/198818989-2fe8210a-be5c-4361-a533-e81e502f031c.png)

**Comment by Uygnis** [comment]
Thanks @personryan
