### ISSUE TITLE
5.2.1 System State Diagram

### ISSUE THREAD

**Issue by DoubleBounce** [personryan/ICT-2101-P4-1#45]
Create the system state diagram.

**Comment by ShaunVSIT** [comment]
State diagram completed as of 25/11:

![Image](https://user-images.githubusercontent.com/91268180/204076153-841dd7ad-2823-4a3d-9683-a4274d8a1b05.png)

**Comment by DoubleBounce** [comment]
Reviewed and seems fine. Will be closing this issue now. 
Closed on 26/11/2022.
