### ISSUE TITLE
Refine critical questions for 1st Client Meeting on 16/09/22

### ISSUE THREAD

**Issue by ShaunVSIT** [personryan/ICT-2101-P4-1#5]
12/9/22: To consolidate and select only critical questions from initial draft, due to limited face to face time with client

**Comment by ShaunVSIT** [comment]
Completed on 15/09/22 meeting our deadline.

**Comment by personryan** [comment]
PFA for the refined questions


![Image](https://user-images.githubusercontent.com/90229655/191940356-6af9c6ec-ead4-42d9-862d-89c7c879b425.png)



![Image](https://user-images.githubusercontent.com/90229655/191940373-1d16745d-c277-4480-ad31-79db92f12473.png)
