### ISSUE TITLE
5.3.2 Control Flow Graph

### ISSUE THREAD

**Issue by personryan** [personryan/ICT-2101-P4-1#56]
11/11/22: To plan for Control Flow Graph

**Comment by personryan** [comment]
26/11/22: Control Flow Graph updated in the docs

![Image](https://user-images.githubusercontent.com/90229655/204073264-112cd092-c545-439c-abfb-1a705fc0520a.png)

**Comment by Uygnis** [comment]
26/11/22: 

![Image](https://user-images.githubusercontent.com/75312898/204076249-d9262d2e-c15b-46cd-b803-da8a628da53f.png)

@personryan made some changes to the cfg to include T/F arrows as well as fixed the incorrect pointing of the for loop at node 15

**Comment by personryan** [comment]
26/11/22: cfg looks good thank you @Uygnis, will be closing the issue
