### ISSUE TITLE
5.2.2.2 Equivalance Partitioning

### ISSUE THREAD

**Issue by Uygnis** [personryan/ICT-2101-P4-1#58]
15/11: Complete Equivalence Partitioning by 23/11/22

**Comment by personryan** [comment]
26/11/22: finalised equivalence partitioning


![Image](https://user-images.githubusercontent.com/90229655/204067793-0780ff79-17dd-42b8-a1cd-824d9658ddd0.png)

**Comment by Uygnis** [comment]
26/11: Made slight changes and included another equivalance partitioning test

![Image](https://user-images.githubusercontent.com/75312898/204076563-74366a45-7237-45a0-83ad-0c6dee5cdba2.png)



![Image](https://user-images.githubusercontent.com/75312898/204076604-0b9c195a-bee6-40fd-88d6-14f93841e701.png)
