### ISSUE TITLE
5.2.2.3 Boundary Value Analysis

### ISSUE THREAD

**Issue by Uygnis** [personryan/ICT-2101-P4-1#59]
15/11: Complete Boundary value analysis by 23/11/22

**Comment by personryan** [comment]
26/11/22: finalised boundary value analysis


![Image](https://user-images.githubusercontent.com/90229655/204067807-f8620b24-5b1a-40f3-a850-85be6b16f0c9.png)

**Comment by Uygnis** [comment]
![Image](https://user-images.githubusercontent.com/75312898/204076316-94992b00-c73f-4d74-a347-7fa0d3d8f1e4.png)

updated to include test data column, test steps, actual outcome and p/f
