### ISSUE TITLE
Calculate Use Case Points(UCP) size estimation

### ISSUE THREAD

**Issue by ShaunVSIT** [personryan/ICT-2101-P4-1#8]
18/9/22: Start of UCP estimation

**Comment by Uygnis** [comment]
UCP calculated. Can take a look and make necessary updates if need to
(For all use cases 1-14)
PFA for the excel used for calculation
https://docs.google.com/spreadsheets/d/1eOHNr6OXjT2t9tRVLz_WXPfS9GM0ILtU2QtpppDTsng/edit?usp=sharing

**Comment by personryan** [comment]
20/9/22: UCP checked looks good, PFA for UCP uploaded to report. (Deadline met)


![Image](https://user-images.githubusercontent.com/90229655/191939680-2f068564-9cf3-43f2-a12c-a31669e2e7a4.png)
