### ISSUE TITLE
Develop detailed Use Cases based on Use Case diagram

### ISSUE THREAD

**Issue by ShaunVSIT** [personryan/ICT-2101-P4-1#9]

**Comment by personryan** [comment]
16/9/22: Finished our use case diagrams, added MoSCow to determine use case's priortiy
(Deadline met)

![Image](https://user-images.githubusercontent.com/90229655/191941314-f134fdcd-3f50-4cad-9ff2-ac345e7bbf6f.png)


![Image](https://user-images.githubusercontent.com/90229655/191941384-18e889c6-1c9a-426d-8e31-e74654ea4096.png)
